<!DOCTYPE html>
<html lang="en">
  <head>
      <meta charset="UTF-8">
      <title>Register</title>
      <link rel="stylesheet" href="/css/output.css">


  </head>

    <body class="min-h-screen font-mono bg-green-100 flex items-center justify-center">
      <div class="w-full max-w-md bg-green-300 rounded-2xl shadow-xl p-8 border border-gray-200">
        <h1 class="text-3xl font-semibold text-gray-900 text-center mb-2">
        Create an account
        </h1>
          <form method="POST" action="/register" class="space-y-6">
            <div>
              <label  class="block text-lg font-bold  text-gray-700 mb-1">
              Username
              </label>
              <input type="text" name="username" class="w-full p-3 border  rounded-lg bg-gray-50" placeholder="Enter a username" required>
            </div>
            <div>
              <label  class="block text-lg font-bold  text-gray-700 mb-1">Password </label>
              <input type="password" name="password" class="w-full p-3 border  rounded-lg bg-gray-50" placeholder="Enter a password" required>
            </div>
    
            <button type="submit" class="w-full py-3 bg-blue-600 text-white  hover:bg-blue-700 transition-all shadow-sm">Create Account</button>
          </form>
          <div class="my-6 border-t border-gray-200"></div>
          <p class="text-center text-gray-600">
              Already have an account?
              <a href="/login" class="text-blue-600 font-medium hover:underline">
                  Log in
              </a>
          </p>
      </div>
    </body>
</html>
